import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/ui/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#1a1c1c",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdcbc",
        "on-error": "#ffffff",
        "on-surface-variant": "#544434",
        background: "#f9f9f9",
        "inverse-surface": "#2f3131",
        "surface-container-highest": "#e2e2e2",
        "on-tertiary": "#ffffff",
        "primary-container": "#ff9f1c",
        "on-primary": "#ffffff",
        "surface-container": "#eeeeee",
        "tertiary-fixed-dim": "#fabb65",
        "inverse-primary": "#ffb86b",
        error: "#ba1a1a",
        "surface-container-high": "#e8e8e8",
        "on-secondary-fixed": "#00201d",
        "secondary-fixed-dim": "#4fdbcc",
        "surface-dim": "#dadada",
        "surface-tint": "#895100",
        "on-tertiary-fixed-variant": "#643f00",
        "surface-container-low": "#f3f3f4",
        "on-secondary": "#ffffff",
        "on-background": "#1a1c1c",
        "inverse-on-surface": "#f0f1f1",
        secondary: "#006a62",
        surface: "#f9f9f9",
        "secondary-fixed": "#70f8e8",
        "on-secondary-fixed-variant": "#005049",
        "surface-variant": "#e2e2e2",
        "outline-variant": "#dac2ae",
        "on-primary-container": "#683c00",
        primary: "#895100",
        "tertiary-container": "#e6a956",
        "on-tertiary-container": "#633f00",
        "primary-fixed-dim": "#ffb86b",
        "on-primary-fixed": "#2c1700",
        "surface-bright": "#f9f9f9",
        "secondary-container": "#70f8e8",
        tertiary: "#835401",
        "tertiary-fixed": "#ffddb5",
        "on-primary-fixed-variant": "#683d00",
        "on-secondary-container": "#007168",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#2a1800",
        outline: "#877462",
        "sage-blue": "#2d3748",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "section-padding": "80px",
        "stack-sm": "8px",
        "container-max": "1280px",
        "stack-lg": "32px",
        "margin-mobile": "16px",
        "stack-md": "16px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-sm": ["14px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};

export default config;
